title: Rose Garden

author:
  name: Rose
  url: https://colleirose.github.io

date_format: "%B %-d, %Y"

### --- Navbar image ---
avatar: "/assets/img/evernight.webp"

### --- Footer ---

# footer social links
social-network-links:
  github: colleirose
  discord: "users/1430291951936208937"

# How to display the link to your website in the footer
url-pretty: "colleirose.github.io"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

### --- Colors ---

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
mobile-theme-col: "rgb(36, 58, 99)"

### General Jekyll/Ruby options

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-seo-tag

sass:
    sass_dir: _sass
    style: compressed

# Jekyll SEO/meta tags options
social:
  name: Rose

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/evernight.webp

# Output options (more information on Jekyll's site)
timezone: "America/Los_Angeles"
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Appraisals
  - theme.gemspec
  - docs/